controllers:
  resource: '../src/Controller/'
  type: annotation
  prefix: /{_locale}
  defaults:
    _locale: '%locale%'

homepage:
  path: /
  controller: App\Controller\MainController::indexAction
  requirements:
    _locale: '%locale%'

  defaults:
    _locale: '%locale%'

    logout:
      path: /logout
