homepage:
  path: /{_locale}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  requirements:
    _locale: '%app_locales%'

  defaults:
    template: homepage.html.twig
    _locale: '%locale%'

    logout:
      path: /logout
