controllers:
  resource: '../src/Controller/'
  type: annotation
  prefix: /{_locale}
  defaults:
    _locale: '%locale%'

homepage:
  path: /{_locale}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  requirements:
    _locale: '%app_locales%'

  defaults:
    _locale: '%locale%'

    logout:
      path: /logout
