App\Entity\City:
    type: entity
    table: city
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titleUk:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_uk
        titleRu:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_ru
        titleEn:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: title_en
        parentId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: parent_id
        type:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        orderNumber:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: order_number
    lifecycleCallbacks: {  }
