App\Entity\Job:
    type: entity
    table: job
    indexes:
        FK_category_id_job:
            columns:
                - category_id
        FK_country_id_job:
            columns:
                - country_id
        FK_user_id_job:
            columns:
                - user_id
        FK_city_id_job:
            columns:
                - city_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        status:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        images:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        files:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        isRemote:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: is_remote
        isPermanent:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: is_permanent
        permanentType:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: permanent_type
        cityOther:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: city_other
        citiesAllowed:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: cities_allowed
        salaryType:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: salary_type
        salaryCurrency:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: salary_currency
        salary:
            type: float
            nullable: true
            precision: 10
            scale: 0
        salaryPayMethod:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: salary_pay_method
        salaryComment:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: salary_comment
        salaryRange:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: salary_range
        salaryRangeFrom:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: salary_range_from
        salaryRangeTo:
            type: float
            nullable: true
            precision: 10
            scale: 0
            column: salary_range_to
        experienceNumber:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: experience_number
        experienceDimension:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: experience_dimension
        seekPeriod:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: seek_period
        seekPeriodDimension:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: seek_period_dimension
        education:
            type: integer
            nullable: true
            options:
                unsigned: false
        ageFrom:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: age_from
        ageTo:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: age_to
        skills:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        languages:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        createdAt:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_at
        updatedAt:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: updated_at
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        city:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                city_id:
                    referencedColumnName: id
            orphanRemoval: false
        country:
            targetEntity: Country
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                country_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
