App\Entity\Language:
    type: entity
    table: language
    indexes:
        FK_lang_id_language:
            columns:
                - lang_id
        FK_user_id_language:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        langLevel:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: lang_level
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        lang:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lang_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
