App\Entity\Migration:
    type: entity
    table: migration
    id:
        version:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        applyTime:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: apply_time
    lifecycleCallbacks: {  }
