App\Entity\Portfolio:
    type: entity
    table: portfolio
    indexes:
        FK_user_id_portfolio:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        order:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        url:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        video:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        images:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
