App\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        username:
            columns:
                - username
        email:
            columns:
                - email
        password_reset_token:
            columns:
                - password_reset_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ''
        authKey:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: auth_key
        passwordHash:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: password_hash
        passwordResetToken:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: password_reset_token
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        status:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '10'
        createdAt:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: created_at
        updatedAt:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: updated_at
        userType:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: user_type
        company:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        newsletter:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
